-- ============================================================
-- SAGRADO E PROFANO — atualização: Categorias
-- Rode isto no SQL Editor do Supabase (não precisa rodar o schema.sql
-- de novo — este arquivo só ADICIONA o que falta).
-- ============================================================

-- ---------- TABELA: categorias ----------
create table if not exists categorias (
  id bigint generated by default as identity primary key,
  nome text not null,
  slug text unique not null,
  cor text not null default '#8b4fc9',
  created_at timestamptz not null default now()
);

alter table categorias enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where tablename='categorias' and policyname='categorias: leitura publica') then
    create policy "categorias: leitura publica" on categorias for select using (true);
  end if;
  if not exists (select 1 from pg_policies where tablename='categorias' and policyname='categorias: escrita publica') then
    create policy "categorias: escrita publica" on categorias for all using (true) with check (true);
  end if;
end $$;

-- ---------- Ligar posts a categorias ----------
alter table posts add column if not exists categoria_id bigint references categorias(id) on delete set null;

-- ---------- Categorias iniciais, com base nos temas já usados nas tags ----------
insert into categorias (nome, slug, cor) values
('Fé', 'fe', '#c9a24a'),
('Desejo', 'desejo', '#7a1f3d'),
('Corpo', 'corpo', '#8b4fc9'),
('Memória', 'memoria', '#5b2a86'),
('Amor', 'amor', '#e8c76a')
on conflict (slug) do nothing;

-- ---------- (opcional) associar os posts de exemplo às novas categorias ----------
update posts set categoria_id = (select id from categorias where slug='fe') where slug in ('antes-da-primeira-palavra','quarenta-noites-sem-deus','ofertas-que-ninguem-pediu');
update posts set categoria_id = (select id from categorias where slug='desejo') where slug='o-barro-que-sonhou';
update posts set categoria_id = (select id from categorias where slug='corpo') where slug='os-ritos-do-corpo';
update posts set categoria_id = (select id from categorias where slug='memoria') where slug in ('contagem-dos-dias-perdidos','a-genealogia-das-sombras');
update posts set categoria_id = (select id from categorias where slug='amor') where slug in ('a-segunda-lei-do-coracao','testamento-para-quem-ficar');
