-- ============================================================
-- SAGRADO E PROFANO — schema para Supabase
-- Rode este arquivo inteiro no SQL Editor do seu projeto Supabase
-- (Supabase Dashboard → SQL Editor → New query → colar → Run)
-- ============================================================

-- Extensão para gerar UUID, caso ainda não esteja habilitada
create extension if not exists "uuid-ossp";

-- ---------- TABELA: livros ----------
create table if not exists livros (
  id bigint generated by default as identity primary key,
  numero text not null,
  nome text not null,
  epigrafe text,
  selado boolean not null default false,
  ordem int not null default 0
);

-- ---------- TABELA: posts ----------
create table if not exists posts (
  id bigint generated by default as identity primary key,
  titulo text not null,
  livro_id bigint references livros(id) on delete set null,
  status text not null default 'rascunho' check (status in ('rascunho','publicado')),
  data date not null default current_date,
  resumo text,
  conteudo text,
  tags text[] default '{}',
  meta_titulo text,
  meta_desc text,
  slug text unique,
  keyword text,
  views int not null default 0,
  created_at timestamptz not null default now()
);

-- ---------- TABELA: comentarios ----------
create table if not exists comentarios (
  id bigint generated by default as identity primary key,
  quem text not null default 'anônimo',
  texto text not null,
  post_id bigint references posts(id) on delete cascade,
  status text not null default 'pendente' check (status in ('pendente','aprovado')),
  created_at timestamptz not null default now()
);

-- ============================================================
-- ROW LEVEL SECURITY
-- Como este blog usa a publishable key (chave pública) direto no
-- navegador, sem login de administradora, as políticas abaixo liberam
-- leitura e escrita para qualquer pessoa que tenha a chave pública.
-- Isso é suficiente para o protótipo funcionar. Antes de divulgar o
-- site publicamente, o ideal é adicionar Supabase Auth e restringir
-- INSERT/UPDATE/DELETE apenas à Nona autenticada.
-- ============================================================
alter table livros enable row level security;
alter table posts enable row level security;
alter table comentarios enable row level security;

create policy "livros: leitura publica" on livros for select using (true);
create policy "livros: escrita publica" on livros for all using (true) with check (true);

create policy "posts: leitura publica" on posts for select using (true);
create policy "posts: escrita publica" on posts for all using (true) with check (true);

create policy "comentarios: leitura publica" on comentarios for select using (true);
create policy "comentarios: escrita publica" on comentarios for all using (true) with check (true);

-- ============================================================
-- SEED — os 6 livros do cânone de Nona
-- ============================================================
insert into livros (numero, nome, epigrafe, selado, ordem) values
('I','Gênesis','No princípio era o silêncio, e o silêncio se chamava Nona.', false, 1),
('II','Êxodo','Toda travessia começa com a coragem de abandonar um deus antigo.', false, 2),
('III','Levítico','Os ritos do corpo também são orações.', false, 3),
('IV','Números','Contei os dias perdidos e ainda faltam mais do que os que restam.', false, 4),
('V','Deuteronômio','A lei que escrevo é só para quem ficar depois de mim.', false, 5),
('VI','Apocalipse','O véu ainda não se rasgou. Em breve.', true, 6);

-- ============================================================
-- SEED — posts de exemplo (usa subconsulta para achar o id do livro pelo número)
-- ============================================================
insert into posts (titulo, livro_id, status, data, resumo, conteudo, tags, meta_titulo, meta_desc, slug, keyword, views)
values
('Antes da Primeira Palavra', (select id from livros where numero='I'), 'publicado', '2026-02-03',
 'Sobre o silêncio que existia antes de qualquer coisa ser dita — e o que ele ainda guarda.',
 E'Antes da primeira palavra havia um silêncio tão espesso que se podia tocá-lo com as mãos. Nona diz que foi nesse silêncio que aprendeu a rezar, muito antes de saber o nome de qualquer deus.\n\nNão era um silêncio vazio. Era um silêncio cheio de tudo o que ainda não tinha coragem de acontecer. Havia nele o formato exato de cada palavra que viria depois — como uma fôrma esperando o barro.\n\nQuando finalmente a primeira palavra foi dita, não foi um grito nem uma ordem. Foi uma confissão. E é assim que todo texto sagrado começa: não com autoridade, mas com a vergonha de existir.',
 array['origem','silêncio','fé'], 'Antes da Primeira Palavra — Sagrado e Profano', 'Um texto de Nona sobre o silêncio que precede toda palavra, e o que ele revela sobre o começo de tudo.', 'antes-da-primeira-palavra', 'silêncio', 842),

('O Barro Que Sonhou', (select id from livros where numero='I'), 'publicado', '2026-02-10',
 'Uma releitura íntima da criação, contada do ponto de vista do próprio barro.',
 E'Diz-se que fomos feitos de barro, mas ninguém pergunta o que o barro sentiu ao ser feito gente. Nona imagina essa cena como quem lembra de um sonho antigo: o barro não queria virar corpo, queria continuar sendo terra, sem pressa, sem nome.\n\nMas alguém soprou. E o barro, contra a própria vontade de permanecer disforme, aprendeu a ter fome, a ter frio, a ter desejo.\n\nTalvez seja por isso que carregamos essa saudade estranha de voltar ao chão. Não é medo da morte — é nostalgia do barro que ainda não tinha sido obrigado a sonhar.',
 array['criação','corpo','desejo'], 'O Barro Que Sonhou — Sagrado e Profano', 'Nona reimagina a criação do ponto de vista do barro, entre a resistência e o desejo de se tornar corpo.', 'o-barro-que-sonhou', 'barro', 611),

('A Travessia do Deserto Interior', (select id from livros where numero='II'), 'publicado', '2026-02-18',
 'Sobre os desertos que atravessamos sem sair do lugar.',
 E'Há travessias que ninguém vê, porque acontecem por dentro. Nona escreve sobre o deserto que se atravessa sem tirar os pés do chão — o deserto de deixar de acreditar em algo que sustentava tudo.\n\nQuarenta dias, diz a história antiga. Nona não sabe quantos foram os seus, só sabe que em algum momento a sede parou de doer e virou hábito.\n\nNo fim de todo deserto há sempre uma promessa — mas às vezes a promessa é apenas a de que se pode continuar andando mesmo sem chegar a lugar nenhum.',
 array['travessia','exílio'], 'A Travessia do Deserto Interior — Sagrado e Profano', 'Um texto sobre os desertos internos que atravessamos ao abandonar antigas certezas.', 'a-travessia-do-deserto-interior', 'deserto', 734),

('Quarenta Noites Sem Deus', (select id from livros where numero='II'), 'rascunho', '2026-03-01',
 'O que resta da fé quando ela se ausenta por um tempo.',
 E'Houve um tempo em que Nona parou de rezar, não por raiva, mas por cansaço. Quarenta noites, conta ela, sem dirigir a palavra a nada além do teto.\n\nNinguém avisa que a ausência de deus também tem seu próprio ritual: acender a luz sozinha, comer sem agradecer, dormir sem pedir perdão por nada.\n\nE então, na noite quarenta e um, sem anúncio nem trombeta, veio de volta — não como certeza, mas como hábito de olhar para cima antes de dormir.',
 array['dúvida','fé'], '', '', 'quarenta-noites-sem-deus', '', 0),

('Os Ritos do Corpo', (select id from livros where numero='III'), 'publicado', '2026-03-09',
 'O corpo como altar, o gesto cotidiano como oferenda.',
 E'Nona acredita que todo gesto repetido vira rito, e todo rito vira uma forma de oração — mesmo quando ninguém o chama assim. Escovar os dentes, acender um cigarro, tocar a própria pele no escuro: tudo isso é liturgia.\n\nA diferença entre o sagrado e o profano, escreve ela, não está no gesto, mas na atenção que se dedica a ele.\n\nPor isso este livro se chama Levítico: porque fala das leis não-escritas do corpo, as que a gente cumpre sem saber que está cumprindo.',
 array['corpo','ritual'], 'Os Ritos do Corpo — Sagrado e Profano', 'Nona escreve sobre como os gestos cotidianos do corpo se tornam formas silenciosas de oração.', 'os-ritos-do-corpo', 'corpo', 958),

('Ofertas Que Ninguém Pediu', (select id from livros where numero='III'), 'publicado', '2026-03-15',
 'Sobre os sacrifícios que fazemos sem que ninguém os tenha exigido.',
 E'Fazemos ofertas o tempo todo, mesmo sem altar. Abrimos mão de coisas que ninguém pediu, na esperança de que isso compre algum tipo de paz.\n\nNona chama isso de "sacrifício sem sacerdote": a dieta que ninguém mandou fazer, o silêncio que ninguém exigiu, o perdão que foi dado antes mesmo do pedido de desculpas.\n\nTalvez a fé mais pura seja essa — a de continuar oferecendo, mesmo sem certeza de que existe alguém do outro lado para receber.',
 array['sacrifício','fé'], 'Ofertas Que Ninguém Pediu — Sagrado e Profano', 'Um texto sobre os pequenos sacrifícios cotidianos que fazemos sem que ninguém os tenha exigido.', 'ofertas-que-ninguem-pediu', 'sacrifício', 503),

('Contagem dos Dias Perdidos', (select id from livros where numero='IV'), 'publicado', '2026-03-22',
 'Um inventário íntimo do tempo que se foi sem deixar endereço.',
 E'Nona começou a contar os dias perdidos como quem faz um censo particular. Não os dias ruins — os dias que simplesmente não deixaram marca nenhuma.\n\nDescobriu que são muitos. Mais do que os dias que lembra com nitidez, mais até do que os dias felizes.\n\nE ainda assim, escreve ela, cada dia perdido também contou para alguma coisa: para o cansaço que a trouxe até aqui, para a paciência que aprendeu sem perceber.',
 array['tempo','memória'], 'Contagem dos Dias Perdidos — Sagrado e Profano', 'Nona faz um inventário íntimo dos dias que passaram sem deixar marca — e do que eles significam.', 'contagem-dos-dias-perdidos', 'tempo', 389),

('A Genealogia das Sombras', (select id from livros where numero='IV'), 'publicado', '2026-03-29',
 'Um mapa de quem nos gerou por dentro, além do sangue.',
 E'Toda pessoa carrega uma genealogia dupla: a do sangue e a das sombras. Nona traça a segunda — as pessoas, medos e silêncios que a geraram por dentro sem parentesco algum.\n\nHá uma avó que nunca conheceu mas cujo jeito de calar herdou. Há um medo que não nasceu com ela, mas que criou raízes como se tivesse.\n\nEscrever essa genealogia, diz Nona, é uma forma de finalmente apresentar essas sombras umas às outras — e talvez, com sorte, fazer as pazes com a árvore inteira.',
 array['herança','sombra'], 'A Genealogia das Sombras — Sagrado e Profano', 'Nona traça a genealogia invisível dos medos e silêncios que a formaram, além do parentesco de sangue.', 'a-genealogia-das-sombras', 'sombra', 445),

('A Segunda Lei do Coração', (select id from livros where numero='V'), 'publicado', '2026-04-05',
 'Quando a primeira lei falha, escreve-se uma segunda, mais honesta.',
 E'A primeira lei do coração de Nona dizia: ame sem medir. Ela falhou algumas vezes, então escreveu uma segunda.\n\nA segunda lei é mais modesta: ame, mas guarde uma chave. Não por desconfiança, mas por respeito à própria sobrevivência.\n\nNão é uma lei mais fria — é uma lei mais velha, escrita por alguém que já sabe que sobreviver ao amor também é uma forma de honrá-lo.',
 array['amor','lei'], 'A Segunda Lei do Coração — Sagrado e Profano', 'Nona escreve sobre a lei mais honesta que aprendeu depois que a primeira, a de amar sem medir, falhou.', 'a-segunda-lei-do-coracao', 'amor', 1204),

('Testamento Para Quem Ficar', (select id from livros where numero='V'), 'publicado', '2026-04-12',
 'O que Nona deixaria escrito se este fosse o último texto.',
 E'Se este fosse o último texto, Nona diz que gostaria que ele servisse de testamento — não de bens, mas de instruções para continuar sentindo depois que ela for embora.\n\nDeixaria escrito: chorem pouco, leiam bastante, não tenham pressa de fechar as feridas alheias.\n\nE deixaria também um pedido final: que o sexto livro, quando vier, seja lido devagar. Porque tudo que é apocalipse também é revelação — e revelação não se apressa.',
 array['legado','despedida'], 'Testamento Para Quem Ficar — Sagrado e Profano', 'Um texto-testamento de Nona, com instruções para quem ficar depois que as palavras dela pararem.', 'testamento-para-quem-ficar', 'legado', 876);

-- ============================================================
-- SEED — comentários de exemplo
-- ============================================================
insert into comentarios (quem, texto, post_id, status, created_at) values
('Marina R.', 'Chorei lendo "A Segunda Lei do Coração". Obrigada por escrever isso, Nona.', (select id from posts where slug='a-segunda-lei-do-coracao'), 'aprovado', now() - interval '2 days'),
('anônimo', 'O texto sobre o barro me fez repensar minha relação com meu próprio corpo.', (select id from posts where slug='o-barro-que-sonhou'), 'pendente', now() - interval '5 days'),
('J.', 'Quando sai o Apocalipse?? Preciso saber.', (select id from posts where slug='testamento-para-quem-ficar'), 'pendente', now() - interval '7 days'),
('Helena', 'Releio "Os Ritos do Corpo" toda vez que preciso me lembrar de ser gentil comigo mesma.', (select id from posts where slug='os-ritos-do-corpo'), 'aprovado', now() - interval '14 days');
